# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-27 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compraprecio',
            unique_together=set([('producto', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='ventaprecio',
            unique_together=set([('producto', 'fecha')]),
        ),
    ]
