# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160827_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AddField(
            model_name='trabajador',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='dpi',
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='foto',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='perfil_usuario'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compraprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_compra', to='main.Producto'),
        ),
        migrations.AlterField(
            model_name='ventaprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_venta', to='main.Producto'),
        ),
    ]
